# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedfast < Formula
  desc "AI-powered PostgreSQL database seeding tool"
  homepage "https://seedfa.st"
  version "2.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.seedfa.st/seedfast/v2.6.1/seedfast_Darwin_x86_64.tar.gz"
      sha256 "6990b6888665c72ae35c379f8c515922d1bd55bdfddfa442cc7ea4fdca4e2c0c"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm?
      url "https://download.seedfa.st/seedfast/v2.6.1/seedfast_Darwin_arm64.tar.gz"
      sha256 "6a9db8adcb32ca033f4eeb034203f07aa18692c9f25c2881dee4a42deb0c3af9"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://download.seedfa.st/seedfast/v2.6.1/seedfast_Linux_x86_64.tar.gz"
      sha256 "79e5ac8bd117cd34eb6175c3857f80e2eea09988d45d7c670d96cd3ed1c02e41"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://download.seedfa.st/seedfast/v2.6.1/seedfast_Linux_arm64.tar.gz"
      sha256 "21c08536a4d59ce22aaa86edea97318f68a4f42fec079db55f262b60844e3b97"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  def caveats
    <<~EOS
      Run `seedfast login` to authenticate with the backend service.
      Then use `seedfast connect` to configure your database connection.
      Finally, run `seedfast seed` to start seeding your database.
    EOS
  end

  test do
    system "#{bin}/seedfast", "version"
  end
end
