# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedfast < Formula
  desc "AI-powered PostgreSQL database seeding tool"
  homepage "https://seedfa.st"
  version "2.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.seedfa.st/seedfast/v2.6.3/seedfast_Darwin_x86_64.tar.gz"
      sha256 "d67897d618e3b358a39e5d450981f57f6c027241bb913886748ed2357bdd1da3"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm?
      url "https://download.seedfa.st/seedfast/v2.6.3/seedfast_Darwin_arm64.tar.gz"
      sha256 "70f5d369ed893292e695234a7bf812659eff241afd70b1264fd25a292e7e9eef"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://download.seedfa.st/seedfast/v2.6.3/seedfast_Linux_x86_64.tar.gz"
      sha256 "357567ae7777241880189a5a97d5f99b329593132657de03fcf2a4a13f0b9a6a"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://download.seedfa.st/seedfast/v2.6.3/seedfast_Linux_arm64.tar.gz"
      sha256 "5c05445f261cfc6b9a88c0c4fc3bb459f0e5734c5907214a2195183d9b4eb383"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  def caveats
    <<~EOS
      Run `seedfast login` to authenticate with the backend service.
      Then use `seedfast connect` to configure your database connection.
      Finally, run `seedfast seed` to start seeding your database.
    EOS
  end

  test do
    system "#{bin}/seedfast", "version"
  end
end
