# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seedfast < Formula
  desc "AI-powered PostgreSQL database seeding tool"
  homepage "https://seedfa.st"
  version "2.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://download.seedfa.st/seedfast/v2.6.4/seedfast_Darwin_x86_64.tar.gz"
      sha256 "2fb8f4c94dcbc7dc114fab54401b6317639ea39c19aab7e520ceb900a888c477"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm?
      url "https://download.seedfa.st/seedfast/v2.6.4/seedfast_Darwin_arm64.tar.gz"
      sha256 "c4cb40f38d29e9ee40aa78db7df2a092975bc7cb3d4f20caa93a4bdd5fc85089"

      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://download.seedfa.st/seedfast/v2.6.4/seedfast_Linux_x86_64.tar.gz"
      sha256 "53013117d3c8fcf0f3d744a95b7c3e49caffb479dca29129272c469b2bb7b7dd"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://download.seedfa.st/seedfast/v2.6.4/seedfast_Linux_arm64.tar.gz"
      sha256 "ecee7f0a238e127c7091c5ef155507e558aea5fd74c58bb316bf37ede3e7e941"
      define_method(:install) do
        bin.install "seedfast"
      end
    end
  end

  def caveats
    <<~EOS
      Run `seedfast login` to authenticate with the backend service.
      Then use `seedfast connect` to configure your database connection.
      Finally, run `seedfast seed` to start seeding your database.
    EOS
  end

  test do
    system "#{bin}/seedfast", "version"
  end
end
